# Generated by Django 4.2.5 on 2023-09-25 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lessson_id',
            new_name='lesson_id',
        ),
    ]
